apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  volumes:
  - name: flexvolume-dir
    hostPath:
      path: /var/lib/kubelet/volumeplugins
      type: DirectoryOrCreate
